# Generated by Django 4.1.1 on 2022-10-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Коллекция')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Коллекции',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('stats', models.TextField(blank=True, verbose_name='Статы')),
                ('photo', models.ImageField(upload_to='photos/cats/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('coll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hero.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Коты',
                'verbose_name_plural': 'Коты',
                'ordering': ['coll', 'time_create'],
            },
        ),
    ]
