# Generated by Django 4.1.1 on 2022-10-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='coll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hero.collection'),
        ),
    ]
